// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4gfGFGbnds-l5aqJtm8Mx4jr7f1IvuOw',
    appId: '1:233710183684:web:f142e814a22c1345b59c51',
    messagingSenderId: '233710183684',
    projectId: 'test1-79ec1',
    authDomain: 'test1-79ec1.firebaseapp.com',
    storageBucket: 'test1-79ec1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBImZIYpSCaLZTPSjnp46VZYoZKN9fdfiU',
    appId: '1:233710183684:android:8ce711f93ed6de8db59c51',
    messagingSenderId: '233710183684',
    projectId: 'test1-79ec1',
    storageBucket: 'test1-79ec1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFReGe_nDGv28u9EIiSJBK_RIi2Rlv_cI',
    appId: '1:233710183684:ios:890b8244a3b05a3eb59c51',
    messagingSenderId: '233710183684',
    projectId: 'test1-79ec1',
    storageBucket: 'test1-79ec1.firebasestorage.app',
    iosClientId: '233710183684-2p4k2h74j25cps4r90uomgk5u0tgf4d0.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleSignIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFReGe_nDGv28u9EIiSJBK_RIi2Rlv_cI',
    appId: '1:233710183684:ios:890b8244a3b05a3eb59c51',
    messagingSenderId: '233710183684',
    projectId: 'test1-79ec1',
    storageBucket: 'test1-79ec1.firebasestorage.app',
    iosClientId: '233710183684-2p4k2h74j25cps4r90uomgk5u0tgf4d0.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleSignIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4gfGFGbnds-l5aqJtm8Mx4jr7f1IvuOw',
    appId: '1:233710183684:web:ce837f7ffdd68b28b59c51',
    messagingSenderId: '233710183684',
    projectId: 'test1-79ec1',
    authDomain: 'test1-79ec1.firebaseapp.com',
    storageBucket: 'test1-79ec1.firebasestorage.app',
  );
}
